### PR TITLE
solve #3 and avoid code duplication

### PR DESCRIPTION
**Pull request by Qeenon**
I'd also suggest suing GitHub actions for tests as CI

### CODE REVIEW

**Comment by modmoto** [comment]
we actually have this built in azure. But i think the test step is not in there, because I dont know the python command for that. It could be added here: https://github.com/w3champions/w3champions-mmr-service/blob/master/azure-pipelines.yml. If someone tells me how you start the python tests, I can integrate it.

**Comment by Qeenon** [comment]
@modmoto you need `pip install pytest` and then just run `pytest`

**Comment by modmoto** [comment]
is there something like npm install that i need to do before to build it?

**Comment by modmoto** [comment]
Ok, i have two read builds now:
https://dev.azure.com/w3champions/w3champions/_build/results?buildId=3813&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5
and
https://dev.azure.com/w3champions/w3champions/_build/results?buildId=3812&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5\

the first one only ran  `pip install pytest` and then `pytest`
second one 
```
pip install pipenv
pipenv install
pip install pytest
pytest
```

we can also run this in a python environment. This was just run as bash. But in then python env it does not know pip and stuff. I guess this is not the way to go.

Any idea? Will google pyhon test in azure now.

**Comment by Qeenon** [comment]
I can try

**Comment by modmoto** [comment]
Ok, now i am that far:
https://dev.azure.com/w3champions/w3champions/_build/results?buildId=3818&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=12f1170f-54f2-53f3-20dd-22fc7dff55f9

```
rootdir: /home/vsts/work/1/s
plugins: cov-2.10.1
collected 0 items / 1 errors
Coverage.py warning: Couldn't parse Python file '/home/vsts/work/1/s/main.py' (couldnt-parse)
Coverage.py warning: Couldn't parse Python file '/home/vsts/work/1/s/main.py' (couldnt-parse)

==================================== ERRORS ====================================
________________________ ERROR collecting test_main.py _________________________
ImportError while importing test module '/home/vsts/work/1/s/test_main.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_main.py:1: in <module>
    from fastapi.testclient import TestClient
E   ImportError: No module named fastapi.testclient
-------- generated xml file: /home/vsts/work/1/s/junit/test-results.xml --------

---------- coverage: platform linux2, python 2.7.17-final-0 ----------
Coverage HTML written to dir htmlcov
Coverage XML written to file coverage.xml

!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.22 seconds =======
```

I think the dependencies are not installed. `pip install pipenv` and `pipenv install` like in the docker file did not work.

**Pull request merged**
